version: '3.9'

services:
  db:
    build:
      context: ./database
    container_name: questionask-db
    restart: always
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - questionask_net
    ports:
      - "5432:5432"
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 512M
        reservations:
          cpus: '0.5'
          memory: 256M

  redis:
    image: redis:7
    container_name: questionask-redis
    restart: unless-stopped
    command: ["redis-server", "--maxmemory", "256mb", "--maxmemory-policy", "allkeys-lru", "--appendonly", "yes"]
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    env_file:
      - .env
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: "0.5"
        reservations:
          memory: 256M
          cpus: "0.3"

  ms-forms:
    build:
      context: ./ms-forms
    container_name: questionask-ms-forms
    restart: always
    env_file:
      - .env
    depends_on:
      - db
      - redis
    ports:
      - "3000:3000"
    volumes:
      - ./ms-forms:/usr/src/app
      - ./uploads:/usr/src/app/uploads
    networks:
      - questionask_net
    command: [ "npm", "start" ]
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: "1.0"
        reservations:
          cpus: '0.3'
          memory: 256M

volumes:
  db_data:
  redis_data:

networks:
  questionask_net:
    driver: bridge
