version: '3.9'

services:
  db:
    build:
      context: ./database
    container_name: questionask-db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - questionask_net
    ports:
      - "5432:5432"  # puedes eliminar esta línea si no necesitas acceso externo

  ms-forms:
    build:
      context: ./ms-forms
    container_name: ms-forms
    restart: always
    environment:
      DATABASE_URL: ${DATABASE_URL}
      JWT_SECRET: ${JWT_SECRET}
      NODE_ENV: ${NODE_ENV}
    depends_on:
      - db
    ports:
      - "3000:3000"
    volumes:
      - ./ms-forms:/usr/src/app
    networks:
      - questionask_net
    command: ["npm", "start"]
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: "1.0"

volumes:
  db_data:

networks:
  questionask_net:
    driver: bridge